title: Natalia Sergeeva # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My passion is organizing information, so I'm a designer with strong technical skills. I use JS, CSS, react.js, and WordPress for web projects. I'm comfortable with the command-line interface and Github.
Working with Adobe products since 1999 has made me quite an expert. The user-centered design was my bachelor's research topic in 2002. 
I keep in mind SEO from the very beginning of web projects. I'm good at finding a balance between best practices in UX and SEO. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/natalia-sergeeva-08118b2b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
